### ISSUE TITLE
Observação

### ISSUE THREAD

**Issue by Evaldo-comp** [marcelomoreira291/Avalia-o-1#1]
https://github.com/marcelomoreira291/Avalia-o-1/blob/96fbc8eb07a203765c649f3a31f3fe0f13adcc9d/Quest%C3%A3o%202.py#L7

A questão pede a metade do quadruplo. `met_quadrupo  = (num * 4) / 2`

**Comment by marcelomoreira291** [comment]
Vishi, erro de interpretação. Obrigado pelo feedback.
